### ISSUE TITLE
Cannot make u-boot

### ISSUE THREAD

**Issue by oldpenguin** [linux-sunxi/sunxi-bsp#12]
Hello
Cannot make u-boot-sunxi. I get the following error.
`make: *** No rule to make target `a13-olinuxino_config'.  Stop.
make[1]: *** [a13-olinuxino_config] Error 1`
I think this issue has been handled previously for other boards but is not working for a13-olinuxino. I think it has to do with uppercase characters in u-boot-sunxi boards.cfg file.
Any solution ?
Thanks

**Comment by techn** [comment]
9c5df3593740948cab732fd24007d861465d39d7 should fix this. Could you verify?

**Comment by oldpenguin** [comment]
Thank you Techn
The compilation of u-boot starts but fails at some point. What I did was
`git pull
make clean
./configure a13-olinuxino
make`

The error msg is:
`make[3]: Leaving directory `/home/asc/projects/olinuxino/a13/sunxi-bsp-20131017/u-boot-sunxi/lib'
cd /home/asc/projects/olinuxino/a13/sunxi-bsp-20131017/build/a13-olinuxino-u-boot/spl/ && arm-linux-gnueabihf-ld.bfd  -T /home/asc/projects/olinuxino/a13/sunxi-bsp-20131017/build/a13-olinuxino-u-boot/spl/u-boot-spl.lds --gc-sections --gc-sections -Bstatic -Ttext 0x20 arch/arm/cpu/armv7/start.o --start-group arch/arm/cpu/armv7/libarmv7.o arch/arm/cpu/armv7/sunxi/libsunxi.o arch/arm/lib/libarm.o board/sunxi/libsunxi.o common/libcommon.o common/spl/libspl.o disk/libdisk.o drivers/i2c/libi2c.o drivers/mmc/libmmc.o drivers/power/libpower.o drivers/serial/libserial.o lib/libgeneric.o --end-group /home/asc/projects/olinuxino/a13/sunxi-bsp-20131017/build/a13-olinuxino-u-boot/spl/arch/arm/lib/eabi_compat.o -L /opt/gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux/bin/../lib/gcc/arm-linux-gnueabihf/4.7.3 -lgcc -Map u-boot-spl.map -o u-boot-spl
arm-linux-gnueabihf-gcc  -g  -Os   -ffunction-sections -fdata-sections -fno-common -ffixed-r8 -msoft-float  -D__KERNEL__ -DCONFIG_SYS_TEXT_BASE=0x4a000000 -I/home/asc/projects/olinuxino/a13/sunxi-bsp-20131017/build/a13-olinuxino-u-boot/include2 -I/home/asc/projects/olinuxino/a13/sunxi-bsp-20131017/build/a13-olinuxino-u-boot/include -I/home/asc/projects/olinuxino/a13/sunxi-bsp-20131017/u-boot-sunxi/include -fno-builtin -ffreestanding -nostdinc -isystem /opt/gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux/bin/../lib/gcc/arm-linux-gnueabihf/4.7.3/include -pipe  -DCONFIG_ARM -D__ARM__ -marm -mno-thumb-interwork -mabi=aapcs-linux -march=armv7-a -Wall -Wstrict-prototypes -fno-stack-protector -Wno-format-nonliteral -Wno-format-security -fstack-usage -mno-unaligned-access     -o /home/asc/projects/olinuxino/a13/sunxi-bsp-20131017/build/a13-olinuxino-u-boot/common/hush.o hush.c -c
board/sunxi/libsunxi.o: In function `sunxi_board_init':
/home/asc/projects/olinuxino/a13/sunxi-bsp-20131017/u-boot-sunxi/board/sunxi/board.c:100: undefined reference to `sunxi_dram_init'
/home/asc/projects/olinuxino/a13/sunxi-bsp-20131017/u-boot-sunxi/board/sunxi/board.c:103: undefined reference to `sunxi_dram_init'
/home/asc/projects/olinuxino/a13/sunxi-bsp-20131017/u-boot-sunxi/board/sunxi/board.c:107: undefined reference to `sunxi_dram_init'`
Hope its enough info to understand whats going on
Regards
António

**Comment by arokux** [comment]
On Fri, Oct 18, 2013 at 10:13 AM, oldpenguin notifications@github.comwrote:

> Thank you Techn
> The compilation of u-boot starts but fails at some point. What I did was
> git pull
> make clean
> ./configure a13-olinuxino
> make

Please read here what you should have done

https://github.com/linux-sunxi/u-boot-sunxi/wiki

Best
Arokux

**Comment by oldpenguin** [comment]
Hello Aroruk
Yes, I see what you mean. But I was trying to use the upper level makefile in sunxi-bsp to compile everything.
Something is not correct with my previous commands. Either `make clean` did not clean the u-boot project and/or `git pull` did not what it is supposed to do.
Anyway I started all over again with
`git clone https://github.com/linux-sunxi/sunxi-bsp.git
./configure a13-olinuxino
make`
and this time everything when smoothly. So I think this issue can be marked as solved.
Thanks again
António
