### ISSUE TITLE
Gooseberry_A721 u-boot support missing

### ISSUE THREAD

**Issue by z000p** [linux-sunxi/sunxi-bsp#2]
Gooseberry_A721 currently lacks u-boot support and cannot build.

**Comment by amery** [comment]
before pushing the changes, can you test http://dl.linux-sunxi.org/amery/sunxi-3.0/20121112-1343/gooseberry_a721_hwpack.tar.xz ?

**Comment by z000p** [comment]
Does it work with a1x-media-create.sh ? That's the only way I know how to build SD-cards for the A10.

**Comment by amery** [comment]
iirc cnxsoft's script only supports .7z hwpacks. but it does work with sunxi-bsp's scripts/sunxi-mediate.create.sh

**Comment by z000p** [comment]
Tried it but got errors:
Disk /dev/sdf: 1023 cylinders, 246 heads, 62 sectors/track

sfdisk: ERROR: sector 0 does not have an msdos signature
 /dev/sdf: unrecognized partition table type
Old situation:
No partitions found
Warning: bad partition start (earliest 68)

sfdisk: bad input
/dev/sdf: failed to repartition media

**Comment by z000p** [comment]
With sunxi-mediate.create.sh that is. Not sure why it didn't like the SD-card.

**Comment by cnxsoft** [comment]
I had this issue before. That's why I added the line:
sudo parted $1 --script mklabel msdos >> ${logfile} 

to a1x-media-create.sh.

I don't know if it is possible to do something similar with sfdisk in sunxi-media-create.sh

**Comment by amery** [comment]
@z000p what size is your card?
@cnxsoft what does that do?

**Comment by z000p** [comment]
8gb

**Comment by cnxsoft** [comment]
It creates an msdos label and fixes "ERROR: sector 0 does not have an msdos signature".

**Comment by amery** [comment]
that's just ranting after zeroing the first MB, the real error seems to be

```
Warning: bad partition start (earliest 68)

sfdisk: bad input
```

and it smells related to 1MB not been multiple of his sector size.... now the thing is how to get the sector size with sfdisk

**Comment by z000p** [comment]
I tried a1x-media-create.sh on it, which runs/boots fine. But the fdisk output looks a bit strange?
Might be something with the card..

Disk /dev/sdf: 7990 MB, 7990149120 bytes
246 heads, 62 sectors/track, 1023 cylinders
Units = cylinders of 15252 \* 512 = 7809024 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk identifier: 0x0008f65d

   Device Boot      Start         End      Blocks   Id  System
/dev/sdf1               1           3       14336    c  W95 FAT32 (LBA)
Partition 1 has different physical/logical beginnings (non-Linux?):
     phys=(0, 32, 33) logical=(0, 33, 3)
Partition 1 has different physical/logical endings:
     phys=(1, 232, 39) logical=(2, 3, 30)
Partition 1 does not end on cylinder boundary.
/dev/sdf2               3        1024     7787520   83  Linux
Partition 2 has different physical/logical beginnings (non-Linux?):
     phys=(1, 232, 40) logical=(2, 3, 31)
Partition 2 has different physical/logical endings:
     phys=(971, 105, 30) logical=(1023, 47, 50)
Partition 2 does not end on cylinder boundary.

**Comment by amery** [comment]
@z000p could you try with http://sprunge.us/NWbZ applied?

**Comment by amery** [comment]
@z000p with all the media-create issue I lost the state of the real issue.... is the provided hardware pack booting your gooseboard fine?

**Comment by z000p** [comment]
I'm getting a bit nervous trying out untested code with partitioning.. don't want my main drive wiped :/

**Comment by z000p** [comment]
Haven't been able to try because of the media-create issue lol

**Comment by z000p** [comment]
Maybe I could try again when I get access to another SD card. That's the only one I have available at the moment

**Comment by amery** [comment]
@z000p tried the patch I gave you for sunxi-media-create.sh ?

**Comment by z000p** [comment]
I noticed some other guys that have Gooseberrys. Hopefully one of them can help out (they might also have serial consoles hooked up for debugging).

**Comment by z000p** [comment]
Gooseberry_A721 has been confirmed to be working. As far as I remember I used the same SD card as the time of the bug report so that issue is solved as well. This report can now be closed!

**Comment by oliv3r** [comment]
Closing per request.
