### ISSUE TITLE
ARM device compilation support

### ISSUE THREAD

**Issue by z000p** [linux-sunxi/sunxi-bsp#3]
Request to add support for running the script on an actual ARM device and not use cross compiling.

**Comment by z000p** [comment]
(sorry for opening a new issue without closing the last one first but I haven't forgotten about it)

**Comment by abvgdeyoj** [comment]
Quite a nice idea. But describe more how you plan to use it please.

**Comment by oliv3r** [comment]
To support this, feel free to send a patch. Quite frankly, I would be supprised if you can't just pass CROSS_COMPILE=mylocalcopmilerprefix- and use your local compiler.
