### ISSUE TITLE
use of $ROOTFS

### ISSUE THREAD

**Issue by Louson** [linux-sunxi/sunxi-bsp#4]
line 198:
if [ "$DEST" = "usr/lib" ]; then
    mv $ROOTFS/lib $ROOTFS/usr

I believe you mean $ROOTFSDIR, because $ROOTFS is null in my case (this could have been dangerous, as it tried to write into /lib)

**Comment by amery** [comment]
the whole chunk is evil. not sure what cnxsoft intended with it. can you try removing it entirely?

**Comment by amery** [comment]
I think http://sprunge.us/HNCN reflects better the spirit of that block, can you test it?  it should move the rootfs files in the hwpack before copying them over.

**Comment by Louson** [comment]
It worked just fine. thanks
