### ISSUE TITLE
How to change the hwpack?

### ISSUE THREAD

**Issue by logbird** [linux-sunxi/sunxi-bsp#6]
I have a hardware adopts the Allwinner 10 chip, http://www.kiwiboard.org/
I can't find support hwpack in configure list.
I want to know do I need to use which hwpack, think you!

**Comment by techn** [comment]
http://linux-sunxi.org/Submitting_Boards

**Comment by techn** [comment]
You could submit your board mem information and fex-file. Or check which board is closest from existing boards by comparing those informations.
