### ISSUE TITLE
ext2/3 drivers

### ISSUE THREAD

**Issue by abvgdeyoj** [linux-sunxi/sunxi-bsp#7]
I am not quite sure, but i think the option:
"Use ext4 for ext2/ext3 file systems" in linux kernel is stable and good enough to be used by default.
It works very well, yet making the kernel smaller.

**Comment by oliv3r** [comment]
I belive a patch for this is in the queue by hramrach. Once that patchset gets merged, it should be all good. Reopen it if this is not the case in a few months time.
