### ISSUE TITLE
u_boot_env_gen ????

### ISSUE THREAD

**Issue by stygmate** [linux-sunxi/sunxi-bsp#9]
the script mk_livesuit_img.sh call the binary u_boot_env_gen at line 69.
but this binary don't seem to work.
i've a message like file not found....
any idea ?

ps: i'm working in ubuntu 64bit.

Ben.

**Comment by hipboi** [comment]
On Aug 21, 2013 11:11 PM, "stygmate" notifications@github.com wrote:

> the script mk_livesuit_img.sh call the binary u_boot_env_gen at line 69.
> but this binary don't seem to work.
> i've a message like file not found....
> any idea ?
> 
> ps: i'm working in ubuntu 64bit.

If you build u-boot of lichee-dev branch, you will get this under tools.

**Comment by sissie** [comment]
installing libc6:i386 solved the problem for me

**Comment by techn** [comment]
yes. part of livesuit toolchain is 32bit and part 64bit. So, 64bit linux with 32bit compat packages are required.
